name: Python app run when pushed to main branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
          CLOUD_API_KEY: ${{secrets.CLOUD_API_KEY}}
          CLOUD_API_SECRET: ${{secrets.CLOUD_API_SECRET}}
          CLOUD_NAME: ${{secrets.CLOUD_NAME}}
          GMAIL_EMAIL: ${{secrets.GMAIL_EMAIL}}
          GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
          IG_ACCESS_TOKEN: ${{secrets.IG_ACCESS_TOKEN}}
          IG_PASSWORD: ${{secrets.IG_PASSWORD}}
          IG_USERNAME: ${{secrets.IG_USERNAME}}
          IG_USER_ID: ${{secrets.IG_USER_ID}}
          WINDY_API_KEY: ${{secrets.WINDY_API_KEY}}
      run: |
        python ./ColorsOfBerlin/main.py
